using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImageUploader.Models
{
    public class Gallery
    {
        //Propperties for our Gallery class, these will be automatic generated by our entity framework
        [Key]
        public int GelleryID { get; set; }
        public string GalleryUrl { get; set; }
        public string Title { get; set; }

        public ICollection<GalleryImage> GalleryImages { get; set; }
    }
}
